#ifndef GRAMMAR_H

#define GRAMMAR_H

#define NUM_RULES 104
#define NUM_TERMINALS 57
#define NUM_NON_TERMINALS 56

enum nonTerminal {
	_OP1, _DECLARESTMT, _SUB_INPUT_PLIST,
	_EXTENDED_VAR, _IDLIST, _SUB_TERM,
	_LVALUEARRSTMT, _SUB_OUTPUT_PLIST,
	_OPTIONAL, _ASSIGNMENTSTMT, _WHICHSTMT,
	_DEFAULT, _PROGRAM, _STATEMENT, _NULLABLECASESTMT,
	_MODULEDECLARATIONS, _ITERATIVESTMT, _FACTOR,
	_SUB_IDLIST, _LVALUEIDSTMT, _CONDITIONALSTMT,
	_INPUT_PLIST, _ANYTERM, _BOOLCONSTT, _DYNAMIC_RANGE,
	_TERM, _SUB_U, _INDEX, _WHICHID, _CASESTMT,
	_OTHERMODULES, _MODULE, _RELATIONALOP, _LOGICALOP,
	_MODULEDEF, _MODULEREUSESTMT, _OUTPUT_PLIST,
	_VAR, _DRIVERMODULE, _NEW_EXPRESSION,
	_RET, _DATATYPE, _STATEMENTS, _ARITHMETICEXPR,
	_RANGE, _SUB_ARITHMETICEXPR, _MODULEDECLARATION,
	_TYPE, _SIMPLESTMT, _EXPRESSION, _N7, _N8,
	_VALUE, _OP2, _IOSTMT, _U
};

enum terminal {
    IDENTIFIER, NUM, RNUM, PLUS, MINUS,
    MUL, DIV, LT, LE, GE,
    GT, EQ, NE, DEF, DRIVERDEF,
    ENDDEF, DRIVERENDDEF, SQBO, SQBC, BO,
    BC, RANGEOP, COLON, ASSIGNOP, SEMICOL,
    COMMA, INTEGER, REAL, BOOLEAN_, OF,
    ARRAY, START, END, DECLARE, MODULE,
    DRIVER, PROGRAM, GET_VALUE, PRINT, USE,
    WITH, PARAMETERS, TRUE_, FALSE_, TAKES,
    INPUT, RETURNS, AND, OR, FOR,
    IN, SWITCH, CASE, BREAK, DEFAULT,
    WHILE, EPSILON, DOLLAR
 };

#endif
